[workspace]
members = ["xtask"]

[package]
name = "madoguchi"
version = "0.4.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
dotenv = "0.15.0"
jwt-simple = "0.11.3"
lazy_static = "1.4.0"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_db_pools = { version = "0.1.0-rc.2", features = ["sqlx_postgres"] }
serde = "1.0.152"
serde_json = "1.0.93"
sqlx = { version = "0.6.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "time", "macros", "json", "offline"] }
chrono = { version = "0.4.23", features = ["serde"] }
quick-xml = { version = "0.27.1", features = ["async-tokio", "serialize"] }
reqwest = { version = "0.11.14", features = ["json", "stream"] }
async-compression = { version = "0.3.15", features = ["gzip", "futures-io"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "tracing-log"] }
tracing-log = "0.1.3"
tracing-opentelemetry = "0.18.0"
tracing-logfmt = "0.3.1"
opentelemetry = { version = "0.19.0", features = ["metrics", "rt-tokio"] }
opentelemetry-zipkin = { version = "0.17.0", features = ["reqwest-client"] }
opentelemetry_sdk = "0.19.0"
opentelemetry_api = "0.19.0"
