[workspace]
members = ["xtask"]

[package]
name = "madoguchi"
version = "0.5.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.1"
dotenv = "0.15.0"
jwt-simple = "0.12.9"
lazy_static = "1.5.0"
rocket = { version = "0.5.1", features = ["json"] }
rocket_db_pools = { version = "0.2.0", features = ["sqlx_postgres"] }
serde = "1.0.204"
serde_json = "1.0.120"
sqlx = { version = "0.7.0", features = [
    "runtime-tokio-rustls",
    "postgres",
    "chrono",
    "time",
    "macros",
    "json",
] }
chrono = { version = "0.4.38", features = ["serde"] }
reqwest = { version = "0.12.5", features = ["json", "stream"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "tracing-log",
] }
tracing-logfmt = "0.3.4"
anda-config = "0.2.3"
webhook = "2.1.2"
