[package]
name = "madoguchi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
reqwest = { version = "0.11.14", features = ["json"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
rocket_db_pools = { version = "0.1.0-rc.2", features = ["sqlx_postgres"] }
serde = "1.0.152"
serde_json = "1.0.93"
sha2 = "0.10.6"
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres", "chrono", "macros", "json"] }
